sky:
  datasource:
    host: 127.0.0.1
    port: 3306
    database: sky_take_out
    username: root
    password: ljr040209.
  jwt:
    user-secret-key: itheima
    user-ttl: 7200000
    user-token-name: userToken
  wechat:
    appid: wx2714016ddce042d8
    secret: 5396a481383385dee3168448f6eed661
    dev-mode: true
#    notify-url: http://27b14551.r6.cpolar.cn/user/order/payment

spring:
  redis:
    host: 192.168.233.145
    port: 6380
    #    password: 123456
    database: 2
